# Generated by Django 3.1.4 on 2021-01-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoscalestaus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_guid', models.CharField(max_length=90)),
                ('app_name', models.CharField(max_length=60)),
                ('previous_count', models.IntegerField(null=True)),
                ('current_count', models.IntegerField(null=True)),
            ],
        ),
    ]
