# Generated by Django 3.1.4 on 2021-02-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoscalestaus',
            name='max_count',
            field=models.IntegerField(null=True),
        ),
    ]
