# Generated by Django 3.1.4 on 2021-02-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_autoscalestaus_max_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoscalestaus',
            name='pd_dedup_key',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
